services:
  db:
    image: mysql:8
    container_name: mysql_fastapi_demo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: fastapi_demo
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
