services:
  db:
    image: mysql:8
    container_name: mysql_fastapi_demo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb

  backend:
    build: .
    container_name: fastapi_demo
    ports:
      - '8000:8000'
    depends_on:
      - db
